collections:
  services:
    label: Services
    folder: content/services
    create: true
    fields:
      - { name: order, label: Order, widget: number }
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: details, label: Details, widget: markdown }
      - { name: icon, label: Icon, widget: string }